[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.1",
    "tarsafe>=0.0.5",
    "crewai>=0.28.8",
    "pyyaml>=6.0",
    "anthropic>=0.7.0",
]
